#!/bin/sh
set -e

# Begin prerm_init
if [ -x "/etc/init.d/boson" ]; then
	invoke-rc.d boson stop || exit $?
fi
# End prerm_init

# Begin prerm_systemd
if [ -d /run/systemd/system ]; then
	deb-systemd-invoke stop 'boson.service' >/dev/null || true
fi
# End prerm_systemd