/*
 * Copyright (c) 2023 -      bosonnetwork.io
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

package io.bosonnetwork.cwt;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.time.Duration;
import java.util.Arrays;
import java.util.Collections;
import java.util.Date;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

import com.fasterxml.jackson.databind.ObjectReader;
import com.fasterxml.jackson.dataformat.cbor.CBORGenerator;

import org.jspecify.annotations.Nullable;

import io.bosonnetwork.Id;
import io.bosonnetwork.Identity;
import io.bosonnetwork.crypto.Signature;
import io.bosonnetwork.json.Json;
import io.bosonnetwork.utils.Hex;

/**
 * Represents a CBOR Web Token (CWT) structured as a COSE_Sign1 (COSE Single Signer Data Object).
 * <p>
 * This class provides a specialized and secure implementation of CWTs, strictly enforcing the
 * use of the EdDSA (Ed25519) signature algorithm. It seamlessly integrates with the Boson Network's
 * cryptographic {@link Identity} and {@link Id} system, ensuring that the {@code "iss"} (Issuer)
 * claim is intrinsically bound to the issuer's public key identifier.
 * <p>
 * <b>Security - the issuer is self-asserted:</b> a token is verified against the Ed25519 public
 * key carried in its own {@code "iss"} claim. A successful {@link #parse(byte[]) parse} therefore
 * proves only that the token was signed by the holder of the key it names as issuer - it does
 * <em>not</em> establish that this issuer is trusted. Callers MUST pin trust by configuring
 * {@link Parser#requireIssuer(Id)} or by validating the {@code "iss"} claim against an allow-list
 * after parsing. A valid signature alone is not authentication.
 * <p>
 * <b>References:</b>
 * <ul>
 *   <li><a href="https://datatracker.ietf.org/doc/html/rfc8392">RFC 8392 - CBOR Web Token</a></li>
 *   <li><a href="https://datatracker.ietf.org/doc/html/rfc8152">RFC 8152 - CBOR Object Signing and Encryption (COSE)</a></li>
 *   <li><a href="https://www.rfc-editor.org/rfc/rfc9052.html">RFC 9052 - COSE: Structures and Process</a></li>
 * </ul>
 * <p>
 * <i>Note: Tokens generated by this class can be independently verified on <a href="https://cwt.cam">cwt.cam</a>.</i>
 *
 * @see SignedCwt.Builder
 */
public class SignedCwt {
	private static final String SIG_STRUCTURE_SIGN_1 = "Signature1";
	private static final byte[] EXTERNAL_AAD = new byte[0];
	private static final int COSE_SIGN_1_TAG = 0xD2; // 0xC0 + 18

	private static final ObjectReader COSE_MAP_READER = Json.cborMapper().readerFor(
			Json.cborMapper().getTypeFactory().constructMapType(LinkedHashMap.class, Integer.class, Object.class));
	private static final ObjectReader COSE_LIST_READER = Json.cborMapper().readerFor(
			Json.cborMapper().getTypeFactory().constructCollectionType(List.class, Object.class));

	private final Map<Integer, Object> protectedHeaders;
	private final Map<Integer, Object> unprotectedHeaders;
	private final Map<Integer, Object> claims;
	private final byte[] signature;

	private SignedCwt(Map<Integer, Object> protectedHeaders, Map<Integer, Object> unprotectedHeaders,
	                  Map<Integer, Object> claims, byte[] signature) {
		this.protectedHeaders = protectedHeaders;
		this.unprotectedHeaders = unprotectedHeaders;
		this.claims = claims;
		this.signature = signature;
	}

	/**
	 * Retrieves the value of a header from either the protected or unprotected header maps.
	 * Protected headers take precedence over unprotected headers.
	 *
	 * @param header the integer key of the header (e.g., from {@link Header}).
	 * @param <T>    the expected type of the header value.
	 * @return the header value, or null if not present.
	 */
	@SuppressWarnings("unchecked")
	public <T> @Nullable T getHeader(int header) {
		if (protectedHeaders.containsKey(header))
			return (T) protectedHeaders.get(header);

		return (T) unprotectedHeaders.get(header);
	}

	/**
	 * Checks if the specified claim is present in the claims map.
	 *
	 * @param claim the integer key of the claim to check for presence.
	 * @return true if the claim is present, false otherwise.
	 */
	public boolean containsClaim(int claim) {
		return claims.containsKey(claim);
	}

	/**
	 * Retrieves the value of a specific claim from the CWT payload.
	 *
	 * @param claim the integer key of the claim (e.g., from {@link Claim}).
	 * @param <T>   the expected type of the claim value.
	 * @return the claim value, or null if not present.
	 * @throws ClassCastException if the stored value is not assignable to the inferred type {@code T}.
	 *         The cast is unchecked and driven entirely by the caller's expected type.
	 */
	@SuppressWarnings("unchecked")
	public <T> @Nullable T getClaim(int claim) {
		return (T) claims.get(claim);
	}

	/**
	 * Retrieves the value of a specific claim as a string.
	 * If the value of the claim is not present, this method returns null.
	 * If the value of the claim is of a type other than String, it is converted to a string.
	 *
	 * @param claim the integer key of the claim to retrieve
	 * @return the claim value as a string, or null if the claim is not present
	 */
	public @Nullable String getClaimAsString(int claim) {
		Object value = claims.get(claim);
		if (value == null)
			return null;

		if (value instanceof String s)
			return s;
		else
			return String.valueOf(value);
	}

	/**
	 * Retrieves the value of a specific claim as an {@code Id}.
	 * If the value of the claim is not present, this method returns {@code null}.
	 * If the value of the claim is a {@code byte[]} or a {@code String}, the method attempts to convert it to an {@code Id}.
	 * If the value cannot be converted, an {@code IllegalStateException} is thrown.
	 *
	 * @param claim the integer key of the claim to retrieve.
	 * @return the claim value as an {@code Id}, or {@code null} if the claim is not present.
	 * @throws IllegalStateException if the claim value cannot be mapped to an {@code Id}.
	 */
	public @Nullable Id getClaimAsId(int claim) {
		Object value = claims.get(claim);
		if (value == null)
			return null;

		if (value instanceof byte[] bs)
			return Id.of(bs);
		else if (value instanceof String s)
			return Id.of(s);
		else
			throw new IllegalStateException("Can not map claim to Id");
	}

	/**
	 * Returns an unmodifiable view of all claims present in the CWT.
	 * <p>
	 * The map itself is read-only, but {@code byte[]} claim values are returned by reference and
	 * must not be mutated by the caller.
	 *
	 * @return an unmodifiable view of the claims.
	 */
	public Map<Integer, Object> getClaims() {
		return Collections.unmodifiableMap(claims);
	}

	/**
	 * Retrieves the cryptographic signature of the CWT.
	 *
	 * @return a copy of the signature bytes.
	 */
	public byte[] getSignature() {
		return signature.clone();
	}

	/**
	 * Checks whether the CWT has expired based on its "exp" (Expiration Time) claim,
	 * strictly (with 0 leeway).
	 *
	 * @return true if the token is expired, false otherwise.
	 */
	public boolean isExpired() {
		return isExpired(0);
	}

	/**
	 * Determines whether the token has expired based on the "exp" (Expiration Time),
	 * "nbf" (Not Before), and "iat" (Issued At) claims. The method considers
	 * specified leeway to account for clock skew.
	 *
	 * @param leeway the number of seconds to adjust the expiration, not-before,
	 *               and issued-at times to allow for clock skew. Must be >= 0.
	 * @return true if the token is considered expired or invalid; false otherwise.
	 * @throws IllegalArgumentException if the leeway is negative.
	 */
	public boolean isExpired(int leeway) {
		if (leeway < 0)
			throw new IllegalArgumentException("leeway must be >= 0");

		long now = System.currentTimeMillis() / 1000;

		if (claims.containsKey(Claim.EXPIRATION.getValue())) {
			Object numObj = getClaim(Claim.EXPIRATION.getValue());
			if (!(numObj instanceof Number exp))
				return true;
			if (exp.longValue() < (now - leeway))
				return true;
		}

		if (claims.containsKey(Claim.NOT_BEFORE.getValue())) {
			Object numObj = getClaim(Claim.NOT_BEFORE.getValue());
			if (!(numObj instanceof Number nbf))
				return true;
			if (nbf.longValue() > (now + leeway))
				return true;
		}

		if (claims.containsKey(Claim.ISSUED_AT.getValue())) {
			Object numObj = getClaim(Claim.ISSUED_AT.getValue());
			if (!(numObj instanceof Number iat))
				return true;
			return iat.longValue() > (now + leeway);
		}

		return false;
	}

	/**
	 * Returns a string representation of the CWT, primarily for debugging purposes.
	 *
	 * @return the string representation.
	 */
	@Override
	public String toString() {
		return Json.toString(protectedHeaders) + "." +
				Json.toString(unprotectedHeaders) + "."
				+ Json.toString(claims) + "."
				+ Hex.encode(signature);
	}

	// Due to the object mapper cannot create CBOR definite-length map and array,
	// So we need to use low-level CBORGenerator to create the expected definite-length object
	private static void writeMap(CBORGenerator gen, Map<Integer, Object> map) throws IOException {
		gen.writeStartObject(map.size());
		for (Map.Entry<Integer, Object> e : map.entrySet()) {
			gen.writeFieldId(e.getKey());
			gen.writeObject(e.getValue());
		}
		gen.writeEndObject();
	}

	private static byte[] encode(Map<Integer, Object> headers) {
		try (ByteArrayOutputStream baos = new ByteArrayOutputStream()) {
			CBORGenerator gen = Json.cborFactory().createGenerator(baos);
			writeMap(gen, headers);
			gen.close();
			return baos.toByteArray();
		} catch (IOException e) {
			throw new IllegalStateException("INTERNAL ERROR: CWT data encode", e);
		}
	}

	private static byte[] getSignData(byte[] protectedHeaders, byte[] payload) {
		try (ByteArrayOutputStream baos = new ByteArrayOutputStream()) {
			CBORGenerator gen = Json.cborFactory().createGenerator(baos);
			gen.writeStartArray(null,4);
			gen.writeString(SIG_STRUCTURE_SIGN_1);
			gen.writeBinary(protectedHeaders);
			gen.writeBinary(EXTERNAL_AAD);
			gen.writeBinary(payload);
			gen.close();
			return baos.toByteArray();
		} catch (IOException e) {
			throw new IllegalStateException("INTERNAL ERROR: CWT data encode", e);
		}
	}

	/**
	 * Parses and verifies a CBOR-encoded Signed CWT (COSE_Sign1).
	 * This method strictly enforces that the algorithm is EdDSA and that the
	 * issuer claim represents a valid Ed25519 public key.
	 *
	 * @param coseBytes the raw CBOR bytes of the CWT.
	 * @return the parsed and verified {@code SignedCwt} object.
	 * @throws CwtException if parsing, structural validation, or cryptographic verification fails.
	 */
	public static SignedCwt parse(byte[] coseBytes) throws CwtException {
		return parse(coseBytes, 0);
	}

	/**
	 * Parses and verifies a CBOR-encoded Signed CWT (COSE_Sign1).
	 * This method strictly enforces that the algorithm is EdDSA and that the
	 * issuer claim represents a valid Ed25519 public key.
	 *
	 * @param coseBytes the raw CBOR bytes of the CWT.
	 * @param leeway the allowed clock skew in seconds for time-based claim validation.
	 * @return the parsed and verified {@code SignedCwt} object.
	 * @throws CwtException if parsing, structural validation, or cryptographic verification fails.
	 * @throws IllegalArgumentException if the specified leeway is negative.
	 */
	public static SignedCwt parse(byte[] coseBytes, int leeway) throws CwtException {
		return parser().setLeeway(leeway).parse(coseBytes);
	}

	/**
	 * Parses and verifies a Signed CWT (COSE_Sign1) from a base64-encoded string representation
	 * with leeway of 0 seconds for claim validation.
	 * This method strictly enforces that the algorithm is EdDSA and that the
	 * issuer claim represents a valid Ed25519 public key.
	 *
	 * @param base64Token the base64-encoded string representation of the CWT.
	 * @return the parsed and verified {@code SignedCwt} object.
	 * @throws CwtException if parsing, structural validation, or cryptographic verification fails.
	 */
	public static SignedCwt parse(String base64Token) throws CwtException {
		return parse(base64Token, 0);
	}

	/**
	 * Parses and verifies a Signed CWT (COSE_Sign1) from a base64-encoded string representation
	 * with the specified leeway for claim validation.
	 * This method strictly enforces that the algorithm is EdDSA and that the
	 * issuer claim represents a valid Ed25519 public key.
	 *
	 * @param base64Token the base64-encoded string representation of the CWT.
	 * @param leeway the allowed clock skew in seconds for time-based claim validation. Must be >= 0.
	 * @return the parsed and verified {@code SignedCwt} object.
	 * @throws CwtException if parsing, structural validation, or cryptographic verification fails.
	 * @throws IllegalArgumentException if the specified leeway is negative.
	 */
	public static SignedCwt parse(String base64Token, int leeway) throws CwtException {
		return parser().setLeeway(leeway).parse(base64Token);
	}

	/**
	 * Creates a new {@code Parser} to parse and validate a {@code SignedCwt}.
	 *
	 * @return a new Parser instance.
	 */
	public static Parser parser() {
		return new Parser();
	}

	/**
	 * Creates a new {@code Builder} to construct a {@code SignedCwt}.
	 *
	 * @param issuer the identity of the token issuer, used to sign the token and set the "iss" claim.
	 * @return a new Builder instance.
	 */
	public static Builder builder(Identity issuer) {
		return new Builder(issuer);
	}

	/**
	 * Builder class for parsing and validating a {@link SignedCwt}.
	 */
	public static class Parser {
		private @Nullable Id expectedIssuer;
		private @Nullable Object expectedSubject;
		private @Nullable Object expectedAudience;
		private boolean ignoreExpiration = false;
		private boolean ignoreNotBefore = false;
		private boolean ignoreIssuedAt = false;
		private int leeway = 0;

		private Parser() {}

		/**
		 * Requires that the token's "iss" (Issuer) claim matches the specified Identity ID.
		 * 
		 * @param issuer the expected issuer.
		 * @return the parser instance.
		 */
		public Parser requireIssuer(Id issuer) {
			this.expectedIssuer = Objects.requireNonNull(issuer);
			return this;
		}

		/**
		 * Requires that the token's "sub" (Subject) claim matches the specified ID.
		 * 
		 * @param subject the expected subject ID.
		 * @return the parser instance.
		 */
		public Parser requireSubject(Id subject) {
			this.expectedSubject = Objects.requireNonNull(subject);
			return this;
		}

		/**
		 * Requires that the token's "sub" (Subject) claim matches the specified String.
		 * 
		 * @param subject the expected subject string.
		 * @return the parser instance.
		 */
		public Parser requireSubject(String subject) {
			this.expectedSubject = Objects.requireNonNull(subject);
			return this;
		}

		/**
		 * Requires that the token's "aud" (Audience) claim matches the specified ID.
		 * 
		 * @param audience the expected audience ID.
		 * @return the parser instance.
		 */
		public Parser requireAudience(Id audience) {
			this.expectedAudience = Objects.requireNonNull(audience);
			return this;
		}

		/**
		 * Requires that the token's "aud" (Audience) claim matches the specified String.
		 * 
		 * @param audience the expected audience string.
		 * @return the parser instance.
		 */
		public Parser requireAudience(String audience) {
			this.expectedAudience = Objects.requireNonNull(audience);
			return this;
		}

		/**
		 * Disables the validation of the "exp" (Expiration Time) claim.
		 * 
		 * @return the parser instance.
		 */
		public Parser ignoreExpiration() {
			this.ignoreExpiration = true;
			return this;
		}

		/**
		 * Disables the validation of the "nbf" (Not Before) claim.
		 * 
		 * @return the parser instance.
		 */
		public Parser ignoreNotBefore() {
			this.ignoreNotBefore = true;
			return this;
		}

		/**
		 * Disables the validation of the "iat" (Issued At) claim.
		 * 
		 * @return the parser instance.
		 */
		public Parser ignoreIssuedAt() {
			this.ignoreIssuedAt = true;
			return this;
		}

		/**
		 * Sets the allowed clock skew leeway (in seconds) for time-based claims.
		 * 
		 * @param leeway the allowed clock skew.
		 * @return the parser instance.
		 */
		public Parser setLeeway(int leeway) {
			if (leeway < 0)
				throw new IllegalArgumentException("leeway must be >= 0");
			this.leeway = leeway;
			return this;
		}

		// Compares a single expected value against a single claim value. A multi-valued ("aud" as a
		// CBOR array) claim is not supported and will not match.
		@SuppressWarnings("BooleanMethodIsAlwaysInverted")
		private boolean match(Object expected, @Nullable Object claim) {
			if (expected instanceof byte[] be && claim instanceof byte[] bc)
				return Arrays.equals(be, bc);

			if (expected instanceof Id id) {
				if (claim instanceof byte[] bc)
					return Arrays.equals(id.bytesUnsafe(), bc);
				if (claim instanceof String s)
					return id.toString().equals(s);
			}

			return Objects.equals(expected, claim);
		}

		/**
		 * Parses and validates the provided CBOR bytes according to the configured constraints.
		 * <p>
		 * <b>Security:</b> the signature is verified against the public key in the token's own
		 * {@code "iss"} claim (self-asserted issuer). Unless {@link #requireIssuer(Id)} was
		 * configured, a successful parse does not authenticate the issuer - validate {@code "iss"}
		 * against a trust anchor yourself. See the {@link SignedCwt class documentation}.
		 *
		 * @param coseBytes the raw CBOR bytes of the CWT.
		 * @return the parsed and verified {@code SignedCwt} object.
		 * @throws CwtException if parsing, structural validation, or cryptographic verification fails.
		 */
		public SignedCwt parse(byte[] coseBytes) throws CwtException {
			/*
			 * RFC8392 A.3 structure:
			 *
			 * 18([
			 *   protected,
			 *   unprotected,
			 *   payload,
			 *   signature
			 * ])
			 *
			 * Jackson does NOT understand CBOR tag 18,
			 * but conveniently to check manually.
			 */
			Objects.requireNonNull(coseBytes);
			if (coseBytes.length == 0)
				throw new InvalidCborTagException("Empty token");

			// Only the canonical single-byte encoding of CBOR tag 18 (0xD2) is accepted, matching
			// what build() emits. Multi-byte tag encodings of the same value are not recognized.
			int tag = Byte.toUnsignedInt(coseBytes[0]);
			if (tag != COSE_SIGN_1_TAG)
				throw new InvalidCborTagException("Unknown CBOR tag: " + tag);

			List<Object> sign1;
			try {
				sign1 = COSE_LIST_READER.readValue(coseBytes);
				if (sign1.size() != 4)
					throw new InvalidCoseStructureException("COSE Structure Array should have 4 elements, actual: " + sign1.size());
			} catch (IOException e) {
				throw new InvalidCoseStructureException("Invalid COSE Structure", e);
			}

			if (!(sign1.get(0) instanceof byte[] protectedHeadersBytes))
				throw new InvalidCoseStructureException("Protected headers should be of type byte[]");

			Map<Integer, Object> protectedHeaders;
			try {
				protectedHeaders = COSE_MAP_READER.readValue(protectedHeadersBytes);
			} catch (IOException e) {
				throw new InvalidCoseStructureException("Invalid protected headers", e);
			}
			Object value = protectedHeaders.get(Header.ALG.getValue());
			if (!(value instanceof Integer alg))
				throw new InvalidAlgorithmException("Invalid algorithm: " + value);
			if (alg != Algorithm.EDDSA.getValue())
				throw new InvalidAlgorithmException("Unsupported algorithm: " + value);

			// RFC 8152/9052 §3.1: a recipient that does not understand a header listed in "crit"
			// MUST reject the token. This implementation understands no critical extensions, so the
			// mere presence of a (non-empty) "crit" header is a rejection.
			Object crit = protectedHeaders.get(Header.CRIT.getValue());
			if (crit != null && !(crit instanceof List<?> l && l.isEmpty()))
				throw new InvalidCoseStructureException("Unsupported critical headers (crit) present");

			if (!(sign1.get(1) instanceof Map<?, ?> uph))
				throw new InvalidCoseStructureException("Unprotected headers should be a map");

			@SuppressWarnings("unchecked")
			Map<Object, Object> map = (Map<Object, Object>) uph;
			Map<Integer, Object> unprotectedHeaders;
			if (map.isEmpty()) {
				unprotectedHeaders = Map.of();
			} else {
				unprotectedHeaders = new LinkedHashMap<>(map.size());
				for (Map.Entry<Object, Object> e : map.entrySet()) {
					if (e.getKey() instanceof Integer k)
						unprotectedHeaders.put(k, e.getValue());
				}
			}

			if (!(sign1.get(2) instanceof byte[] payload))
				throw new InvalidCoseStructureException("Payload should be of type byte[]");

			Map<Integer, Object> claims;
			try {
				claims = COSE_MAP_READER.readValue(payload);
			} catch (IOException e) {
				throw new InvalidCoseStructureException("Invalid claims", e);
			}

			Object issuerObj = claims.get(Claim.ISSUER.getValue());
			if (!(issuerObj instanceof byte[] issuer) || issuer.length != Signature.PublicKey.BYTES)
				throw new InvalidIssuerKeyException("Invalid issuer key");

			if (expectedIssuer != null) {
				if (!Arrays.equals(issuer, expectedIssuer.bytesUnsafe()))
					throw new InvalidClaimException("Issuer mismatch");
			}

			if (expectedSubject != null) {
				if (!match(expectedSubject, claims.get(Claim.SUBJECT.getValue())))
					throw new InvalidClaimException("Subject mismatch");
			}

			if (expectedAudience != null) {
				if (!match(expectedAudience, claims.get(Claim.AUDIENCE.getValue())))
					throw new InvalidClaimException("Audience mismatch");
			}

			Signature.PublicKey issuerPublicKey;
			try {
				issuerPublicKey = Signature.PublicKey.fromBytes(issuer);
			} catch (Exception e) {
				throw new InvalidIssuerKeyException("Invalid issuer key");
			}

			if (!(sign1.get(3) instanceof byte[] signature))
				throw new InvalidCoseStructureException("Signature should be of type byte[]");
			if (signature.length != Signature.BYTES)
				throw new InvalidCoseStructureException("Invalid signature length: " + signature.length);

			byte[] toSign = getSignData(protectedHeadersBytes, payload);
			if (!issuerPublicKey.verify(toSign, signature))
				throw new InvalidSignatureException("Verification failed");

			long now = System.currentTimeMillis() / 1000;

			if (!ignoreExpiration && claims.containsKey(Claim.EXPIRATION.getValue())) {
				Object expObj = claims.get(Claim.EXPIRATION.getValue());
				if (!(expObj instanceof Number exp))
					throw new TokenExpiredException("Invalid expiration claim");
				if (exp.longValue() < (now - leeway))
					throw new TokenExpiredException("Expired at: " + exp);
			}

			if (!ignoreNotBefore && claims.containsKey(Claim.NOT_BEFORE.getValue())) {
				Object nbfObj = claims.get(Claim.NOT_BEFORE.getValue());
				if (!(nbfObj instanceof Number nbf))
					throw new NotBeforeException("Invalid not-before claim");
				if (nbf.longValue() > (now + leeway))
					throw new NotBeforeException("Not before: " + nbf);
			}

			if (!ignoreIssuedAt && claims.containsKey(Claim.ISSUED_AT.getValue())) {
				Object iatObj = claims.get(Claim.ISSUED_AT.getValue());
				if (!(iatObj instanceof Number iat))
					throw new InvalidIssuedAtException("Invalid issued-at claim");
				if (iat.longValue() > (now + leeway))
					throw new InvalidIssuedAtException("Issued at future: " + iat);
			}

			return new SignedCwt(protectedHeaders, unprotectedHeaders, claims, signature);
		}

		/**
		 * Parses the given Base64-encoded token and returns a SignedCwt object.
		 *
		 * @param base64Token the Base64-encoded token to be parsed
		 * @return a SignedCwt object representing the parsed token
		 * @throws CwtException if there is an error during parsing
		 */
		public SignedCwt parse(String base64Token) throws CwtException {
			if (base64Token == null)
				throw new InvalidCoseStructureException("Token cannot be null");

			byte[] coseBytes;
			try {
				coseBytes = Json.BASE64_DECODER.decode(base64Token);
			} catch (IllegalArgumentException e) {
				throw new InvalidCoseStructureException("Invalid base64 token", e);
			}
			return parse(coseBytes);
		}
	}

	/**
	 * Builder class for constructing a {@link SignedCwt}.
	 */
	public static class Builder {
		private final Identity issuer;

		private final Map<Integer, Object> protectedHeaders;
		private final Map<Integer, Object> unprotectedHeaders;
		private final Map<Integer, Object> claims;

		private Builder(Identity issuer) {
			this.issuer = issuer;

			this.protectedHeaders = new LinkedHashMap<>();
			this.unprotectedHeaders = new LinkedHashMap<>();
			this.claims = new LinkedHashMap<>();

			protectedHeaders.put(Header.ALG.getValue(), Algorithm.EDDSA.getValue());
			claims.put(Claim.ISSUER.getValue(), issuer.getId().bytesUnsafe());
		}

		/**
		 * Adds a protected header to the CWT.
		 *
		 * @param header the integer key of the header.
		 * @param value  the value of the header.
		 * @return the builder instance.
		 */
		public Builder protectedHeader(int header, Object value) {
			protectedHeaders.put(header, value);
			return this;
		}

		/**
		 * Adds an unprotected header to the CWT.
		 *
		 * @param header the integer key of the header.
		 * @param value  the value of the header.
		 * @return the builder instance.
		 */
		public Builder unprotectedHeader(int header, Object value) {
			unprotectedHeaders.put(header, value);
			return this;
		}

		/**
		 * Adds a custom claim to the CWT payload.
		 * Note: The "iss" (Issuer) claim is managed automatically and cannot be set manually.
		 *
		 * @param claim the integer key of the claim.
		 * @param value the value of the claim.
		 * @return the builder instance.
		 * @throws IllegalArgumentException if an attempt is made to manually set the Issuer claim.
		 */
		public Builder claim(int claim, Object value) {
			if (claim == Claim.ISSUER.getValue())
				throw new IllegalArgumentException("Issuer is managed, cannot set manually");
			claims.put(claim, value);
			return this;
		}

		/**
		 * Sets the "sub" (Subject) claim using an {@link Id}.
		 *
		 * @param subject the subject identifier.
		 * @return the builder instance.
		 */
		public Builder subject(Id subject) {
			Objects.requireNonNull(subject);
			claims.put(Claim.SUBJECT.getValue(), subject.bytesUnsafe());
			return this;
		}

		/**
		 * Sets the "sub" (Subject) claim using a String.
		 *
		 * @param subject the subject string.
		 * @return the builder instance.
		 */
		public Builder subject(String subject) {
			Objects.requireNonNull(subject);
			claims.put(Claim.SUBJECT.getValue(), subject);
			return this;
		}

		/**
		 * Sets the "aud" (Audience) claim using an {@link Id}.
		 *
		 * @param audience the audience identifier.
		 * @return the builder instance.
		 */
		public Builder audience(Id audience) {
			Objects.requireNonNull(audience);
			claims.put(Claim.AUDIENCE.getValue(), audience.bytesUnsafe());
			return this;
		}

		/**
		 * Sets the "aud" (Audience) claim using a String.
		 *
		 * @param audience the audience string.
		 * @return the builder instance.
		 */
		public Builder audience(String audience) {
			Objects.requireNonNull(audience);
			claims.put(Claim.AUDIENCE.getValue(), audience);
			return this;
		}

		/**
		 * Sets the "exp" (Expiration Time) claim.
		 *
		 * @param expiration the exact date of expiration.
		 * @return the builder instance.
		 */
		public Builder expiration(Date expiration) {
			Objects.requireNonNull(expiration);
			long exp = expiration.getTime() / 1000;
			claims.put(Claim.EXPIRATION.getValue(), exp);
			return this;
		}

		/**
		 * Sets the "exp" (Expiration Time) claim based on a duration from the current time.
		 *
		 * @param expiration the duration until expiration.
		 * @return the builder instance.
		 */
		public Builder expiration(Duration expiration) {
			Objects.requireNonNull(expiration);
			long exp = (System.currentTimeMillis() + expiration.toMillis()) / 1000;
			claims.put(Claim.EXPIRATION.getValue(), exp);
			return this;
		}

		/**
		 * Sets the "nbf" (Not Before) claim.
		 *
		 * @param notBefore the exact date before which the token must not be accepted.
		 * @return the builder instance.
		 */
		public Builder notBefore(Date notBefore) {
			Objects.requireNonNull(notBefore);
			long nbf = notBefore.getTime() / 1000;
			claims.put(Claim.NOT_BEFORE.getValue(), nbf);
			return this;
		}

		/**
		 * Sets the "nbf" (Not Before) claim based on a duration from the current time.
		 *
		 * @param notBefore the duration before which the token must not be accepted.
		 * @return the builder instance.
		 */
		public Builder notBefore(Duration notBefore) {
			Objects.requireNonNull(notBefore);
			long nbf = (System.currentTimeMillis() + notBefore.toMillis()) / 1000;
			claims.put(Claim.NOT_BEFORE.getValue(), nbf);
			return this;
		}

		/**
		 * Sets the "nbf" (Not Before) claim to the current time.
		 *
		 * @return the builder instance.
		 */
		public Builder notBeforeNow() {
			long nbf = System.currentTimeMillis() / 1000;
			claims.put(Claim.NOT_BEFORE.getValue(), nbf);
			return this;
		}

		/**
		 * Sets the "iat" (Issued At) claim.
		 *
		 * @param issuedAt the exact date of issuance.
		 * @return the builder instance.
		 */
		public Builder issuedAt(Date issuedAt) {
			Objects.requireNonNull(issuedAt);
			long iat = issuedAt.getTime() / 1000;
			claims.put(Claim.ISSUED_AT.getValue(), iat);
			return this;
		}

		/**
		 * Sets the "iat" (Issued At) claim to the current time.
		 *
		 * @return the builder instance.
		 */
		public Builder issuedAtNow() {
			long iat = System.currentTimeMillis() / 1000;
			claims.put(Claim.ISSUED_AT.getValue(), iat);
			return this;
		}

		/**
		 * Sets the "cti" (CWT ID) claim using a byte array.
		 *
		 * @param id the unique token identifier.
		 * @return the builder instance.
		 */
		public Builder tokenId(byte[] id) {
			Objects.requireNonNull(id);
			claims.put(Claim.CWT_ID.getValue(), id);
			return this;
		}

		/**
		 * Sets the "cti" (CWT ID) claim using a String.
		 *
		 * @param id the unique token identifier string.
		 * @return the builder instance.
		 */
		public Builder tokenId(String id) {
			Objects.requireNonNull(id);
			claims.put(Claim.CWT_ID.getValue(), id);
			return this;
		}

		/**
		 * Sets the "nonce" claim.
		 *
		 * @param nonce the nonce byte array.
		 * @return the builder instance.
		 */
		public Builder nonce(byte[] nonce) {
			Objects.requireNonNull(nonce);
			claims.put(Claim.NONCE.getValue(), nonce);
			return this;
		}

		/**
		 * Sets the "scope" claim using a byte array.
		 *
		 * @param scope the scope byte array.
		 * @return the builder instance.
		 */
		public Builder scope(byte[] scope) {
			Objects.requireNonNull(scope);
			claims.put(Claim.SCOPE.getValue(), scope);
			return this;
		}

		/**
		 * Sets the "scope" claim using a String.
		 *
		 * @param scope the scope string.
		 * @return the builder instance.
		 */
		public Builder scope(String scope) {
			Objects.requireNonNull(scope);
			claims.put(Claim.SCOPE.getValue(), scope);
			return this;
		}

		/**
		 * Sets the "client_id" claim using an {@link Id}.
		 *
		 * @param clientId the client identifier.
		 * @return the builder instance.
		 * @throws NullPointerException if the provided clientId is null.
		 */
		public Builder clientId(Id clientId) {
			Objects.requireNonNull(clientId);
			claims.put(Claim.CLIENT_ID.getValue(), clientId.bytesUnsafe());
			return this;
		}

		/**
		 * Sets the "client_id" claim in the CWT payload using the provided client identifier string.
		 *
		 * @param clientId the client identifier to set.
		 * @return the builder instance.
		 * @throws NullPointerException if the provided clientId is null.
		 */
		public Builder clientId(String clientId) {
			Objects.requireNonNull(clientId);
			claims.put(Claim.CLIENT_ID.getValue(), clientId);
			return this;
		}

		/**
		 * Builds and signs the CWT.
		 * Generates the COSE_Sign1 structure, applies the cryptographic signature using
		 * the issuer's identity, and encodes the final token into CBOR format.
		 *
		 * @return the fully constructed and signed CBOR-encoded CWT.
		 */
		public byte[] build() {
			byte[] protectedHeadersBytes = encode(protectedHeaders);
			byte[] payload = encode(claims);

			byte[] toSign = getSignData(protectedHeadersBytes, payload);
			byte[] signature = issuer.sign(toSign);

			try (ByteArrayOutputStream baos = new ByteArrayOutputStream()) {
				baos.write((byte) COSE_SIGN_1_TAG);
				CBORGenerator gen = Json.cborFactory().createGenerator(baos);
				gen.writeStartArray(null, 4);
				gen.writeBinary(protectedHeadersBytes);
				writeMap(gen, unprotectedHeaders);
				gen.writeBinary(payload);
				gen.writeBinary(signature);
				gen.close();
				return baos.toByteArray();
			} catch (IOException e) {
				throw new IllegalStateException("INTERNAL ERROR: CWT data encode", e);
			}
		}

		/**
		 * Encodes the constructed and signed CBOR Web Token (CWT) into a Base64 string.
		 * This method uses the Base64Url encoder to convert the byte array representation
		 * of the CWT into a Base64-encoded format suitable for transmission or storage.
		 *
		 * @return a Base64-encoded string representation of the constructed CWT.
		 */
		public String buildToString() {
			return Json.BASE64_ENCODER.encodeToString(build());
		}
	}
}