/*
 * Copyright (c) 2023 -      bosonnetwork.io
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

package io.bosonnetwork.cwt;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.time.Duration;
import java.util.Collections;
import java.util.Date;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

import com.fasterxml.jackson.databind.ObjectReader;
import com.fasterxml.jackson.dataformat.cbor.CBORGenerator;

import io.bosonnetwork.Id;
import io.bosonnetwork.Identity;
import io.bosonnetwork.crypto.Signature;
import io.bosonnetwork.json.Json;
import io.bosonnetwork.utils.Hex;

/**
 * Represents a CBOR Web Token (CWT) structured as a COSE_Sign1 (COSE Single Signer Data Object).
 * <p>
 * This class provides a specialized and secure implementation of CWTs, strictly enforcing the
 * use of the EdDSA (Ed25519) signature algorithm. It seamlessly integrates with the Boson Network's
 * cryptographic {@link Identity} and {@link Id} system, ensuring that the {@code "iss"} (Issuer)
 * claim is intrinsically bound to the issuer's public key identifier.
 * <p>
 * <b>References:</b>
 * <ul>
 *   <li><a href="https://datatracker.ietf.org/doc/html/rfc8392">RFC 8392 - CBOR Web Token</a></li>
 *   <li><a href="https://datatracker.ietf.org/doc/html/rfc8152">RFC 8152 - CBOR Object Signing and Encryption (COSE)</a></li>
 *   <li><a href="https://www.rfc-editor.org/rfc/rfc9052.html">RFC 9052 - COSE: Structures and Process</a></li>
 * </ul>
 * <p>
 * <i>Note: Tokens generated by this class can be independently verified on <a href="https://cwt.cam">cwt.cam</a>.</i>
 *
 * @see SignedCwt.Builder
 */
public class SignedCwt {
	private static final String SIG_STRUCTURE_SIGN_1 = "Signature1";
	private static final byte[] EXTERNAL_AAD = new byte[0];
	private static final int COSE_SIGN_1_TAG = 0xD2; // 0xC0 + 18

	private static final ObjectReader COSE_MAP_READER = Json.cborMapper().readerFor(
			Json.cborMapper().getTypeFactory().constructMapType(LinkedHashMap.class, Integer.class, Object.class));
	private static final ObjectReader COSE_LIST_READER = Json.cborMapper().readerFor(
			Json.cborMapper().getTypeFactory().constructCollectionType(List.class, Object.class));

	private final Map<Integer, Object> protectedHeaders;
	private final Map<Integer, Object> unprotectedHeaders;
	private final Map<Integer, Object> claims;
	private final byte[] signature;

	private SignedCwt(Map<Integer, Object> protectedHeaders, Map<Integer, Object> unprotectedHeaders,
	                  Map<Integer, Object> claims, byte[] signature) {
		this.protectedHeaders = protectedHeaders;
		this.unprotectedHeaders = unprotectedHeaders;
		this.claims = claims;
		this.signature = signature;
	}

	/**
	 * Retrieves the value of a header from either the protected or unprotected header maps.
	 * Protected headers take precedence over unprotected headers.
	 *
	 * @param header the integer key of the header (e.g., from {@link Header}).
	 * @param <T>    the expected type of the header value.
	 * @return the header value, or null if not present.
	 */
	@SuppressWarnings("unchecked")
	public <T> T getHeader(int header) {
		if (protectedHeaders.containsKey(header))
			return (T) protectedHeaders.get(header);

		return (T) unprotectedHeaders.get(header);
	}

	/**
	 * Retrieves the value of a specific claim from the CWT payload.
	 *
	 * @param claim the integer key of the claim (e.g., from {@link Claim}).
	 * @param <T>   the expected type of the claim value.
	 * @return the claim value, or null if not present.
	 */
	@SuppressWarnings("unchecked")
	public <T> T getClaim(int claim) {
		return (T) claims.get(claim);
	}

	/**
	 * Returns an unmodifiable map of all claims present in the CWT.
	 *
	 * @return a map of claims.
	 */
	public Map<Integer, Object> getClaims() {
		return Collections.unmodifiableMap(claims);
	}

	/**
	 * Retrieves the cryptographic signature of the CWT.
	 *
	 * @return the signature bytes.
	 */
	public byte[] getSignature() {
		return signature;
	}

	/**
	 * Checks whether the CWT has expired based on its "exp" (Expiration Time) claim.
	 * If the claim is not present, the token is not considered expired.
	 * If the claim is present but malformed, it is considered expired for safety.
	 *
	 * @return true if the token is expired, false otherwise.
	 */
	public boolean isExpired() {
		if (!claims.containsKey(Claim.EXPIRATION.getValue()))
			return false;

		Object expObj = getClaim(Claim.EXPIRATION.getValue());
		if (!(expObj instanceof Number exp))
			return true;
		return exp.longValue() < (System.currentTimeMillis()) / 1000;
	}

	/**
	 * Returns a string representation of the CWT, primarily for debugging purposes.
	 *
	 * @return the string representation.
	 */
	@Override
	public String toString() {
		return Json.toString(protectedHeaders) + "." +
				Json.toString(unprotectedHeaders) + "."
				+ Json.toString(claims) + "."
				+ Hex.encode(signature);
	}

	/*/
	private static byte[] encode(Object o) {
		try {
			return Json.cborMapper().writeValueAsBytes(o);
		} catch (IOException e) {
			throw new IllegalStateException("INTERNAL ERROR: CWT data encode", e);
		}
	}
	*/

	// Due to the object mapper cannot create CBOR definite-length map and array,
	// So we need use low-level CBORGenerator to create the expected definite-length object
	private static void writeMap(CBORGenerator gen, Map<Integer, Object> map) throws IOException {
		gen.writeStartObject(map.size());
		for (Map.Entry<Integer, Object> e : map.entrySet()) {
			gen.writeFieldId(e.getKey());
			gen.writeObject(e.getValue());
		}
		gen.writeEndObject();
	}

	private static byte[] encode(Map<Integer, Object> headers) {
		try (ByteArrayOutputStream baos = new ByteArrayOutputStream()) {
			CBORGenerator gen = Json.cborFactory().createGenerator(baos);
			writeMap(gen, headers);
			gen.close();
			return baos.toByteArray();
		} catch (IOException e) {
			throw new IllegalStateException("INTERNAL ERROR: CWT data encode", e);
		}
	}

	private static byte[] getSignData(byte[] protectedHeaders, byte[] payload) {
		try (ByteArrayOutputStream baos = new ByteArrayOutputStream()) {
			CBORGenerator gen = Json.cborFactory().createGenerator(baos);
			// noinspection deprecation
			gen.writeStartArray(4);
			gen.writeString(SIG_STRUCTURE_SIGN_1);
			gen.writeBinary(protectedHeaders);
			gen.writeBinary(EXTERNAL_AAD);
			gen.writeBinary(payload);
			gen.close();
			return baos.toByteArray();
		} catch (IOException e) {
			throw new IllegalStateException("INTERNAL ERROR: CWT data encode", e);
		}
	}

	/**
	 * Parses and verifies a CBOR-encoded Signed CWT (COSE_Sign1).
	 * This method strictly enforces that the algorithm is EdDSA and that the
	 * issuer claim represents a valid Ed25519 public key.
	 *
	 * @param coseBytes the raw CBOR bytes of the CWT.
	 * @return the parsed and verified {@code SignedCwt} object.
	 * @throws CwtException if parsing, structural validation, or cryptographic verification fails.
	 */
	public static SignedCwt parse(byte[] coseBytes) throws CwtException {
		/*
		 * RFC8392 A.3 structure:
		 *
		 * 18([
		 *   protected,
		 *   unprotected,
		 *   payload,
		 *   signature
		 * ])
		 *
		 * Jackson does NOT understand CBOR tag 18,
		 * but conveniently to check manually.
		 */

		// CBOR tag 18
		int tag = Byte.toUnsignedInt(coseBytes[0]);
		if (tag != COSE_SIGN_1_TAG)
			throw new InvalidCborTagException("Unknown CBOR tag: " + tag);

		// COSE Structure Array: 4 items for the signed CWT
		List<Object> sign1;
		try {
			sign1 = COSE_LIST_READER.readValue(coseBytes);
			if (sign1.size() != 4)
				throw new InvalidCoseStructureException("COSE Structure Array should have 4 elements, actual: " + sign1.size());
		} catch (IOException e) {
			throw new InvalidCoseStructureException("Invalid COSE Structure", e);
		}

		// protected headers
		if (!(sign1.get(0) instanceof byte[] protectedHeadersBytes))
			throw new InvalidCoseStructureException("Protected headers should be of type byte[]");

		Map<Integer, Object> protectedHeaders;
		try {
			protectedHeaders = COSE_MAP_READER.readValue(protectedHeadersBytes);
		} catch (IOException e) {
			throw new InvalidCoseStructureException("Invalid protected headers", e);
		}
		Object value = protectedHeaders.get(Header.ALG.getValue());
		if (!(value instanceof Integer alg))
			throw new InvalidAlgorithmException("Invalid algorithm: " + value);
		if (alg != Algorithm.EDDSA.getValue())
			throw new InvalidAlgorithmException("Unsupported algorithm: " + value);

		// unprotectedHeaders
		if (!(sign1.get(1) instanceof Map<?, ?> uph))
			throw new InvalidCoseStructureException("Unprotected headers should be a map");

		@SuppressWarnings("unchecked")
		Map<Object, Object> map = (Map<Object, Object>) uph;
		Map<Integer, Object> unprotectedHeaders;
		if (map.isEmpty()) {
			unprotectedHeaders = Map.of();
		} else {
			unprotectedHeaders = new LinkedHashMap<>(map.size());
			for (Map.Entry<Object, Object> e : map.entrySet()) {
				if (e.getKey() instanceof Integer k)
					unprotectedHeaders.put(k, e.getValue());
			}
		}

		// payload / claims
		if (!(sign1.get(2) instanceof byte[] payload))
			throw new InvalidCoseStructureException("Payload should be of type byte[]");

		Map<Integer, Object> claims;
		try {
			claims = COSE_MAP_READER.readValue(payload);
		} catch (IOException e) {
			throw new InvalidCoseStructureException("Invalid claims", e);
		}

		Object issuerObj = claims.get(Claim.ISSUER.getValue());
		if (!(issuerObj instanceof byte[] issuer) || issuer.length != Signature.PublicKey.BYTES)
			throw new InvalidIssuerKeyException("Invalid issuer key");

		Signature.PublicKey issuerPublicKey;
		try {
			issuerPublicKey = Signature.PublicKey.fromBytes(issuer);
		} catch (Exception e) {
			throw new InvalidIssuerKeyException("Invalid issuer key");
		}

		if (!(sign1.get(3) instanceof byte[] signature))
			throw new InvalidCoseStructureException("Signature should be of type byte[]");
		if (signature.length != Signature.BYTES)
			throw new InvalidCoseStructureException("Invalid signature length: " + signature.length);

		byte[] toSign = getSignData(protectedHeadersBytes, payload);
		if (!issuerPublicKey.verify(toSign, signature))
			throw new InvalidSignatureException("Verification failed");

		long now = System.currentTimeMillis() / 1000;

		if (claims.containsKey(Claim.EXPIRATION.getValue())) {
			Object expObj = claims.get(Claim.EXPIRATION.getValue());
			if (!(expObj instanceof Number exp))
				throw new TokenExpiredException("Invalid expiration claim");
			if (exp.longValue() < now)
				throw new TokenExpiredException("Expired at: " + exp);
		}

		if (claims.containsKey(Claim.NOT_BEFORE.getValue())) {
			Object nbfObj = claims.get(Claim.NOT_BEFORE.getValue());
			if (!(nbfObj instanceof Number nbf))
				throw new NotBeforeException("Invalid not-before claim");
			if (nbf.longValue() > now)
				throw new NotBeforeException("Not before: " + nbf);
		}

		return new SignedCwt(protectedHeaders, unprotectedHeaders, claims, signature);
	}

	/**
	 * Creates a new {@code Builder} to construct a {@code SignedCwt}.
	 *
	 * @param issuer the identity of the token issuer, used to sign the token and set the "iss" claim.
	 * @return a new Builder instance.
	 */
	public static Builder builder(Identity issuer) {
		return new Builder(issuer);
	}

	/**
	 * Builder class for constructing a {@link SignedCwt}.
	 */
	public static class Builder {
		private final Identity issuer;
		private long leeway;

		private final Map<Integer, Object> protectedHeaders;
		private final Map<Integer, Object> unprotectedHeaders;
		private final Map<Integer, Object> claims;

		private Builder(Identity issuer) {
			this.issuer = issuer;
			this.leeway = 0;

			this.protectedHeaders = new LinkedHashMap<>();
			this.unprotectedHeaders = new LinkedHashMap<>();
			this.claims = new LinkedHashMap<>();

			protectedHeaders.put(Header.ALG.getValue(), Algorithm.EDDSA.getValue());
			claims.put(Claim.ISSUER.getValue(), issuer.getId().bytes());
		}

		/**
		 * Adds a protected header to the CWT.
		 *
		 * @param header the integer key of the header.
		 * @param value  the value of the header.
		 * @return the builder instance.
		 */
		public Builder protectedHeader(int header, Object value) {
			protectedHeaders.put(header, value);
			return this;
		}

		/**
		 * Adds an unprotected header to the CWT.
		 *
		 * @param header the integer key of the header.
		 * @param value  the value of the header.
		 * @return the builder instance.
		 */
		public Builder unprotectedHeader(int header, Object value) {
			unprotectedHeaders.put(header, value);
			return this;
		}

		/**
		 * Adds a custom claim to the CWT payload.
		 * Note: The "iss" (Issuer) claim is managed automatically and cannot be set manually.
		 *
		 * @param claim the integer key of the claim.
		 * @param value the value of the claim.
		 * @return the builder instance.
		 * @throws IllegalArgumentException if an attempt is made to manually set the Issuer claim.
		 */
		public Builder claim(int claim, Object value) {
			if (claim == Claim.ISSUER.getValue())
				throw new IllegalArgumentException("Issuer is managed, cannot set manually");
			claims.put(claim, value);
			return this;
		}

		/**
		 * Sets the "sub" (Subject) claim using an {@link Id}.
		 *
		 * @param subject the subject identifier.
		 * @return the builder instance.
		 */
		public Builder subject(Id subject) {
			Objects.requireNonNull(subject);
			claims.put(Claim.SUBJECT.getValue(), subject.bytes());
			return this;
		}

		/**
		 * Sets the "sub" (Subject) claim using a String.
		 *
		 * @param subject the subject string.
		 * @return the builder instance.
		 */
		public Builder subject(String subject) {
			Objects.requireNonNull(subject);
			claims.put(Claim.SUBJECT.getValue(), subject);
			return this;
		}

		/**
		 * Sets the "aud" (Audience) claim using an {@link Id}.
		 *
		 * @param audience the audience identifier.
		 * @return the builder instance.
		 */
		public Builder audience(Id audience) {
			Objects.requireNonNull(audience);
			claims.put(Claim.AUDIENCE.getValue(), audience.bytes());
			return this;
		}

		/**
		 * Sets the "aud" (Audience) claim using a String.
		 *
		 * @param audience the audience string.
		 * @return the builder instance.
		 */
		public Builder audience(String audience) {
			Objects.requireNonNull(audience);
			claims.put(Claim.AUDIENCE.getValue(), audience);
			return this;
		}

		/**
		 * Sets the allowed clock skew leeway (in seconds) for time-based claims like expiration and not-before.
		 *
		 * @param leeway the leeway in seconds.
		 * @return the builder instance.
		 */
		public Builder leeway(long leeway) {
			this.leeway = leeway;
			return this;
		}

		/**
		 * Sets the "exp" (Expiration Time) claim.
		 *
		 * @param expiration the exact date of expiration.
		 * @return the builder instance.
		 */
		public Builder expiration(Date expiration) {
			Objects.requireNonNull(expiration);
			long exp = expiration.getTime() / 1000 + leeway;
			claims.put(Claim.EXPIRATION.getValue(), exp);
			return this;
		}

		/**
		 * Sets the "exp" (Expiration Time) claim based on a duration from the current time.
		 *
		 * @param expiration the duration until expiration.
		 * @return the builder instance.
		 */
		public Builder expiration(Duration expiration) {
			Objects.requireNonNull(expiration);
			long exp = (System.currentTimeMillis() + expiration.toMillis()) / 1000 + leeway;
			claims.put(Claim.EXPIRATION.getValue(), exp);
			return this;
		}

		/**
		 * Sets the "nbf" (Not Before) claim.
		 *
		 * @param notBefore the exact date before which the token must not be accepted.
		 * @return the builder instance.
		 */
		public Builder notBefore(Date notBefore) {
			Objects.requireNonNull(notBefore);
			long nbf = notBefore.getTime() / 1000 - leeway;
			claims.put(Claim.NOT_BEFORE.getValue(), nbf);
			return this;
		}

		/**
		 * Sets the "nbf" (Not Before) claim based on a duration from the current time.
		 *
		 * @param notBefore the duration before which the token must not be accepted.
		 * @return the builder instance.
		 */
		public Builder notBefore(Duration notBefore) {
			Objects.requireNonNull(notBefore);
			long nbf = (System.currentTimeMillis() + notBefore.toMillis()) / 1000 - leeway;
			claims.put(Claim.NOT_BEFORE.getValue(), nbf);
			return this;
		}

		/**
		 * Sets the "nbf" (Not Before) claim to the current time.
		 *
		 * @return the builder instance.
		 */
		public Builder notBeforeNow() {
			long nbf = System.currentTimeMillis() / 1000 - leeway;
			claims.put(Claim.NOT_BEFORE.getValue(), nbf);
			return this;
		}

		/**
		 * Sets the "iat" (Issued At) claim.
		 *
		 * @param issuedAt the exact date of issuance.
		 * @return the builder instance.
		 */
		public Builder IssuedAt(Date issuedAt) {
			Objects.requireNonNull(issuedAt);
			long iat = issuedAt.getTime() / 1000;
			claims.put(Claim.ISSUED_AT.getValue(), iat);
			return this;
		}

		/**
		 * Sets the "iat" (Issued At) claim to the current time.
		 *
		 * @return the builder instance.
		 */
		public Builder IssuedAtNow() {
			long iat = System.currentTimeMillis() / 1000;
			claims.put(Claim.ISSUED_AT.getValue(), iat);
			return this;
		}

		/**
		 * Sets the "cti" (CWT ID) claim using a byte array.
		 *
		 * @param id the unique token identifier.
		 * @return the builder instance.
		 */
		public Builder tokenId(byte[] id) {
			Objects.requireNonNull(id);
			claims.put(Claim.CWT_ID.getValue(), id);
			return this;
		}

		/**
		 * Sets the "nonce" claim.
		 *
		 * @param nonce the nonce byte array.
		 * @return the builder instance.
		 */
		public Builder nonce(byte[] nonce) {
			Objects.requireNonNull(nonce);
			claims.put(Claim.NONCE.getValue(), nonce);
			return this;
		}

		/**
		 * Sets the "scope" claim using a byte array.
		 *
		 * @param scope the scope byte array.
		 * @return the builder instance.
		 */
		public Builder scope(byte[] scope) {
			Objects.requireNonNull(scope);
			claims.put(Claim.SCOPE.getValue(), scope);
			return this;
		}

		/**
		 * Sets the "scope" claim using a String.
		 *
		 * @param scope the scope string.
		 * @return the builder instance.
		 */
		public Builder scope(String scope) {
			Objects.requireNonNull(scope);
			claims.put(Claim.SCOPE.getValue(), scope.getBytes(StandardCharsets.UTF_8));
			return this;
		}

		/**
		 * Sets the "cti" (CWT ID) claim using a String.
		 *
		 * @param id the unique token identifier string.
		 * @return the builder instance.
		 */
		public Builder tokenId(String id) {
			Objects.requireNonNull(id);
			claims.put(Claim.CWT_ID.getValue(), id.getBytes(StandardCharsets.UTF_8));
			return this;
		}

		/**
		 * Builds and signs the CWT.
		 * Generates the COSE_Sign1 structure, applies the cryptographic signature using
		 * the issuer's identity, and encodes the final token into CBOR format.
		 *
		 * @return the fully constructed and signed CBOR-encoded CWT.
		 */
		public byte[] build() {
			byte[] protectedHeadersBytes = encode(protectedHeaders);
			byte[] payload = encode(claims);

			byte[] toSign = getSignData(protectedHeadersBytes, payload);
			byte[] signature = issuer.sign(toSign);

			try (ByteArrayOutputStream baos = new ByteArrayOutputStream()) {
				baos.write((byte) COSE_SIGN_1_TAG);
				CBORGenerator gen = Json.cborFactory().createGenerator(baos);
				// noinspection deprecation
				gen.writeStartArray(4);
				gen.writeBinary(protectedHeadersBytes);
				writeMap(gen, unprotectedHeaders);
				gen.writeBinary(payload);
				gen.writeBinary(signature);
				gen.close();
				return baos.toByteArray();
			} catch (IOException e) {
				throw new IllegalStateException("INTERNAL ERROR: CWT data encode", e);
			}
		}
	}
}